# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_deepcorr_wrappers", use_symbols = TRUE, package_name = "deepcorr")

#' @usage NULL
#' @useDynLib deepcorr, .registration = TRUE
NULL

hello <- function() .Call(wrap__hello)

echo <- function(argument) .Call(wrap__echo, argument)

add <- function(x, y) .Call(wrap__add, x, y)

subtract <- function(x, y) .Call(wrap__subtract, x, y)

multiply <- function(x, y) .Call(wrap__multiply, x, y)

divide <- function(x, y) .Call(wrap__divide, x, y)

exponent <- function(x, y) .Call(wrap__exponent, x, y)

normalize <- function(data, method, epsilon = NULL) .Call(wrap__normalize, data, method, epsilon)


# nolint end
